name: flutterlist
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.2.4
  flutter_gravatar: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
